@echo off
Call clean.bat
xelatex mcmpaper
bibtex mcmpaper
xelatex mcmpaper
xelatex mcmpaper
bibtex mcmpaper
xelatex mcmpaper
xelatex mcmpaper
pdflatex mcmpapersummarysheet
pdflatex mcmpapersummarysheet
pdflatex main
pdflatex main
start main.pdf